import Navbar from "@/layouts/Navbar/Navbar";
import "../globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const locale = params.locale;

  return (
    <html lang={locale}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
